### ISSUE TITLE
Undefined function or variable 'LBHJ_theorem1'

### ISSUE THREAD

**Issue by PaulMDiaz** [happyhongt/An-efficient-method-for-robust-projection-matrix-design#1]
Hello,

I am attempting to use the function effect_lambda_func.m

When I try and use the function I get the error: 

Undefined function or variable 'LBJH_theorem1'

Any advice?

Thanks,
Paul

I also noticed you deleted the file Robust_Projection_Matrix.p was this intentional?

**Comment by hongtao-argmin** [comment]
Thank you for your interests. I am sorry that I do not reply it in time. I will find a time to check it and fix it later today.

**Comment by hongtao-argmin** [comment]
I check it. The thing is that I change the function name after I updating ``Robust_Projection_Matrix.p''. So I delete it. Actually, this function is written for finding a proper trade-off parameter through line search in a given range. You can write it by yourself by using ``Robust_Projection_Matrix.p''. Thank you.
